name: Compile me daddy
on:
  push:
    branches: [ senpai ]
  
jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
      
      - name : 1 - Checkout
        uses: actions/checkout@v2

      - name: 2 - compile source code
        run: mkdir compiled && /usr/bin/gcc something.c -o compiled/something
      
      - name: 3 - upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux build
          path: compiled