
on:
  push:
    branches: [ senpai ]
  
jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: 1 - create tmp folder
        run: mkdir tmp && cd tmp
      
      - name : 2 - clone
        uses: actions/checkout@v2
        with:
          path: tmp

      - name: 3 - compile source code
        run: gcc -o compiled something.c
      
      - name: 3 - upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: tmp